"""Tables added

Revision ID: 08b13ea3e620
Revises: 
Create Date: 2020-08-30 00:32:03.408504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08b13ea3e620'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('tid')
    )
    op.create_table('customer',
    sa.Column('cid', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.tid'], ),
    sa.PrimaryKeyConstraint('cid')
    )
    op.create_table('slot',
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.Column('time', sa.Text(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.tid'], ),
    sa.PrimaryKeyConstraint('sid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slot')
    op.drop_table('customer')
    op.drop_table('ticket')
    # ### end Alembic commands ###
