"""updated models

Revision ID: 10d1ede932d1
Revises: 08b13ea3e620
Create Date: 2020-08-30 13:33:46.621676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10d1ede932d1'
down_revision = '08b13ea3e620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slot')
    op.add_column('customer', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('customer', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('customer', 'phone',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint(None, 'customer', type_='foreignkey')
    op.drop_column('customer', 'ticket_id')
    op.drop_column('customer', 'cid')
    op.add_column('ticket', sa.Column('cid', sa.Integer(), nullable=False))
    op.add_column('ticket', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('ticket', sa.Column('slot', sa.String(length=10), nullable=True))
    op.create_foreign_key(None, 'ticket', 'customer', ['cid'], ['id'])
    op.drop_column('ticket', 'tid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('tid', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'ticket', type_='foreignkey')
    op.drop_column('ticket', 'slot')
    op.drop_column('ticket', 'id')
    op.drop_column('ticket', 'cid')
    op.add_column('customer', sa.Column('cid', sa.INTEGER(), nullable=False))
    op.add_column('customer', sa.Column('ticket_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'customer', 'ticket', ['ticket_id'], ['tid'])
    op.alter_column('customer', 'phone',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('customer', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('customer', 'id')
    op.create_table('slot',
    sa.Column('sid', sa.INTEGER(), nullable=False),
    sa.Column('time', sa.TEXT(), nullable=True),
    sa.Column('ticket_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.tid'], ),
    sa.PrimaryKeyConstraint('sid')
    )
    # ### end Alembic commands ###
